openapi: 3.0.1
info:
  contact:
    email: christo.delange@roadsync.com
  description: This API allows the Roadsync clients to manage aspects of the RoadSync service via an API.
  license:
    name: Copyright (c) 2020, RoadSync Inc.
  title: Client API v1.8 authenticated brokers API
  version: 1.8.45
  x-api-id: 3ea39084-d8df-11ea-ad77-0017b600647f
  x-audience: external-partner
servers:
- url: https://client-api.staging.roadsync.com/{basePath}
  variables:
    Product:
      default: ClientApi
    basePath:
      default: v1
security:
- api_key: []
- session_token: []
tags:
- name: brokers
paths:
  /brokers:
    get:
      summary: Get All Brokers
      tags:
      - brokers
      responses:
        '200':
          $ref: '#/components/responses/getBrokers'
      operationId: get-brokers
      x-stoplight:
        id: bfwgk2oy30fv2
      security:
      - x-api-key: []
      description: Return a list of all the brokers linked to your API Key.
  /brokers/{broker_id}:
    parameters:
    - schema:
        $ref: '#/components/schemas/id'
      name: broker_id
      in: path
      required: true
    get:
      summary: Get a Single Broker
      responses:
        '200':
          $ref: '#/components/responses/getBroker'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      operationId: get-brokers-id
      x-stoplight:
        id: l4z7ugj0eh570
      tags:
      - brokers
      description: Get a single broker.
      security:
      - x-api-key: []
components:
  schemas:
    id:
      type: integer
      x-stoplight:
        id: f7ra661j53v04
      example: 87346
      title: id
      description: The id number of the object being returned.
    brokerName:
      title: broker_name
      type: string
      x-stoplight:
        id: xpgfc7nsg07fw
      description: The name of the broker.
      example: Atlanta Brokerage
    city:
      title: city
      x-stoplight:
        id: 8ypbld5r20d6o
      type: string
      description: A valid city in the United States.
      example: Atlanta
    postalCode:
      title: postal_code
      x-stoplight:
        id: v5t2utdpxdar3
      type: string
      description: A valid postal code in the United States.
      example: '30306'
    phoneNumber:
      title: phone_number
      x-stoplight:
        id: coa4x7lscfh80
      type: string
      description: A valid phone number belonging to a person or company.
      example: '3243444347'
    emailAddressBroker:
      type: string
      x-stoplight:
        id: 4b1lw9uxlo2od
      description: A valid email belonging to the Broker, where remittance emails will be received.
      title: email_address_broker
      example: virginia@atlantabrokerage.com
    brokerIdResponse:
      title: broker_id_response
      type: integer
      x-stoplight:
        id: a6k2b2ugy6fg0
      example: 66305
      description: The identifier of a Broker to which the Payee has been assigned.
    broker:
      title: broker
      x-stoplight:
        id: yzi5j2dpnmvz5
      type: object
      description: The full broker object.
      properties:
        id:
          $ref: '#/components/schemas/brokerIdResponse'
        name:
          $ref: '#/components/schemas/brokerName'
          x-stoplight:
            id: xt85gf89sf1lq
        email_address:
          $ref: '#/components/schemas/emailAddressBroker'
          x-stoplight:
            id: p64zvat285o5f
        phone_number:
          $ref: '#/components/schemas/phoneNumber'
          x-stoplight:
            id: 9uub6sogbv2t8
        address_line_one:
          $ref: '#/components/schemas/addressLineOne'
          x-stoplight:
            id: ytowepra805bj
        address_line_two:
          $ref: '#/components/schemas/addressLineTwo'
          x-stoplight:
            id: a9d1w5ey3q3wm
        address_city:
          $ref: '#/components/schemas/city'
          x-stoplight:
            id: m40v647wog3ij
        address_state:
          $ref: '#/components/schemas/state'
          x-stoplight:
            id: 4mw54g2kaopkv
        address_zip:
          $ref: '#/components/schemas/postalCode'
          x-stoplight:
            id: 65em4nwp8t9lx
        ach_funding_source_id:
          $ref: '#/components/schemas/fundingSourceId'
          x-stoplight:
            id: lh0wjz5u0ywwn
        paper_check_funding_source_id:
          $ref: '#/components/schemas/fundingSourceId'
          x-stoplight:
            id: awyhftcgfj055
        wallet_funding_source_id:
          $ref: '#/components/schemas/fundingSourceId'
          x-stoplight:
            id: gh7wkzac7k9s8
    addressLineOne:
      title: address_line_one
      x-stoplight:
        id: p3a1crckckndd
      type: string
      description: The valid address of a person or business in the United States.
      example: 715 Peachtree St
    state:
      title: state
      x-stoplight:
        id: xwqz3invlqyrz
      type: string
      description: A valid 2 character state code in the United States.
      example: GA
    addressLineTwo:
      title: address_line_two
      x-stoplight:
        id: jpnvzmg54ky3l
      type: string
      nullable: true
      description: If necessary, add a second line of the address in the United States.
      example: APT 23
    fundingSourceId:
      title: funding_source_id
      x-stoplight:
        id: 62r95b324501y
      $ref: '#/components/schemas/id'
      description: Id representing the funding source (papercheck, ach or wallet).
  responses:
    getBroker:
      description: Response from /brokers GET
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
              - $ref: '#/components/schemas/broker'
    getBrokers:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              id:
                $ref: '#/components/schemas/brokerIdResponse'
              $ref: '#/components/schemas/broker'
  securitySchemes:
    api_key:
      in: header
      name: x-api-key
      type: apiKey
      x-apikeyInfoFunc: client_api_server.controllers.authorization_controller.check_api_key
    session_token:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-apikeyInfoFunc: client_api_server.controllers.authorization_controller.check_session_token
