openapi: 3.2.0
info:
  title: Payment API v0 Ping API
  version: 0.5.13
  license:
    name: Copyright (c) 2022, RoadSync Inc.
  description: The Payment API gives you the ability to take payments.
servers:
- url: https://test.api.roadsync.app/v0/payment
  description: Sandbox/Test Payment API
- url: https://api.roadsync.app/v0/payment
  description: Production Payment API
- url: '{server}'
  description: Development
  variables:
    server:
      default: https://dev.api.roadsync.app/v0/payment
tags:
- name: Ping
paths:
  /ping:
    get:
      tags:
      - Ping
      operationId: ping_get
      description: Ping the payment-api service
      summary: Ping the payment-api service.
      responses:
        '200':
          description: Service available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: API service available, but there was an issue with the api key configuration on the request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: '#/components/schemas/Errors'
      security: []
components:
  schemas:
    Errors:
      type: array
      description: A list of errors that occurred during payment processing
      items:
        $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        code:
          type: string
          description: The error code
        title:
          type: string
          description: Summary of error
    PaymentResponse:
      type: object
      additionalProperties: false
      properties:
        data:
          type: object
          description: The Payment object returned by the create call
          properties:
            id:
              type: string
              description: The id of the payment
            checkNumber:
              type: string
              description: The number of the check that was created, only returned for 'efscheck and tchek' paymentType
            status:
              type: string
              description: The status of the payment
            reason:
              type: string
              description: A description on why a payment is in `failed` status
            fields:
              type: array
              description: Fields to be collected from the user for certain payment types.
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the field to collect
                  required:
                    type: boolean
                    description: True if field is required
        errors:
          $ref: '#/components/schemas/Errors'
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-api-key
      in: header
